apiVersion: "v1"
kind: Pod
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  containers:
    - name: kafka-ui
      image:  provectuslabs/kafka-ui
      env:
      - name: KAFKA_CLUSTERS_0_NAME
        valueFrom:
          secretKeyRef:
            name: pds-kafka-demo-secret
            key: KF_SERVER
      - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
        valueFrom:
          secretKeyRef:
            name: pds-kafka-demo-secret
            key: KF_SERVER
      - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
        value: SASL_PLAINTEXT
      - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
        value: PLAIN     
      - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
        valueFrom:
          secretKeyRef:
            name: pds-kafka-demo-secret
            key: KF_CNX_STRING
      ports:
      - containerPort: 8080
        name: web
        protocol: TCP
#      volumeMounts:
#        - mountPath: "/tmp"
#          name: temp-vol
#  volumes:
#    - name: temp-vol
#      persistentVolumeClaim:
#        claimName: pvc-name

