apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-producer-kafka
  labels:
    app: order-producer-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-producer-kafka
  template:
    metadata:
      labels:
        app: order-producer-kafka
    spec:
      containers:
      - env:
        - name: KF_SERVER
          valueFrom:
            secretKeyRef:
              name: pds-kafka-demo-secret
              key: KF_SERVER
        - name: KF_USERNAME
          valueFrom:
            secretKeyRef:
              name: pds-kafka-demo-secret
              key: KF_USERNAME
        - name: KF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pds-kafka-demo-secret
              key: KF_PASSWORD
        - name: KF_TOPIC
          valueFrom:
            secretKeyRef:
              name: pds-kafka-demo-secret
              key: KF_TOPIC
        name: order-producer-kafka
        image: jowings/py-kafka:1.09
        imagePullPolicy: Always
        command: ["python3"]
        args: ["order_producer.py"]
